Create test.yml
Gazzell/ludoteca-app pull request #1
Opened 2023-02-28 21:23 UTC by Guillermo-prog

Configuración del flujo que lanzara los tests en las PR a main mediante GithubActions

2023-02-28 21:39 UTC, Gazzell commented
parece que el package.json y el lock no están sincronizados. Prueba a borrar el nodeModules y hacer npm install

2023-03-01 08:36 UTC, Guillermo-prog commented
Pero esto no es un poco raro? Porque esta haciendo comprobaciones de test basándose en el fichero de configuración de tests que estoy subiendo en esta misma PR, es decir todavía no debería de comprobar nada porque no esta subido, no?

2023-03-01 08:38 UTC, Gazzell commented
Las comprobaciones se hacen según están los ficheros. En esta rama ya está la config para hacer las comprobaciones, así que las ejecuta. Es una forma de saber que todo funciona además. He creado un commit para actualizar el package.lock

2023-03-01 08:45 UTC, Gazzell requested changes
Es un buen primer paso, pero creo que faltan algunas cosas:
- Si se ha subido a un CI, habría que generar aut'maticamente el enlace a la build, así el reviewer puede probarlo
- El título de la PR tiene que ser más descriptivo, igual que el de los commits. En un commit deberías hacer referencia a la funcionalidad que implementas y no a los ficheros que tocas (por ejemplo: 'chore: add build scripts to check errors and upload to CI')
- Fijate que pongo 'chore: ' En este proyecto no lo estamos usando, pero es algo típico para generar versiones automáticamente y es bueno que uses tags en los commits: https://www.conventionalcommits.org/en/v1.0.0/
- Si me pones como reviewer me notifica git de que has subido cosas. 

Intenta generar el link a la build y crea otro commit con ello en esta PR.

2023-03-01 09:35 UTC, Gazzell commented on .github/workflows/test.yml
> +        node-version: [14.x, 16.x, 18.x]
No creo que necesitemos comprobaciones para todas estas versiones de node. Déjalo en 18.x y ya vale

2023-03-01 09:41 UTC, Guillermo-prog commented on .github/workflows/test.yml
> +        node-version: [14.x, 16.x, 18.x]
okeyy perfecto

2023-03-01 17:27 UTC, Gazzell commented on .github/workflows/test.yml
> +    branches: [ "main" ]
no tengo claro que tengas que hacer nada en estas ramas. Lo suyo sería hacer deploy de la rama actual, para poder probar lo que queremos mergear antes de que esté en main. Esto siempre que sea posible, ya que para ello hace falta poder tener diferentes targets en gh-pages (nombre rama, etc), poder hacer que se borren cuando se mergea la PR o bien, tener solamente abierta una PR cada vez.... Cómo lo ves?

2023-03-01 17:30 UTC, Gazzell commented on .eslintignore
> +src/*.test.js
no creo que se abuena idea quitar el linter de los tests.

2023-03-01 17:31 UTC, Gazzell commented on .husky/pre-push
> +npm run test
quita este de aquí y añadelo al pre-commit, para que pase tests en commit. En push yo no haría nada...

2023-03-01 17:34 UTC, Gazzell commented
Supongo que tengo que añadir alguna key o permiso a la config del repo para que esto funcione. Dime qué es lo que hay que cambiar

2023-03-05 17:41 UTC, Gazzell approved these changes
ok!!

2023-03-05 17:42 UTC, merged