feat: funcionalidad de logout con proteccion de las rutas
Gazzell/ludoteca-app pull request #11
Opened 2023-03-31 10:35 UTC by Guillermo-prog

Para probar la funcionalidad utilizar el mismo usuario y contraseña (prueba1234@gmail.com:prueba1234). Y el botón logout en la pagina Home.

2023-03-31 16:22 UTC, Gazzell requested changes
He eliminado el último commit porque si que parece que hacía falta.  Por lo demas, tiene buena pinta.

Como apunte, tendrías que intentar hacer commits más pequeños, por ejemplo, uno para meter la lib de estilos, otro para aplicar los estilos en los componentes y otro para la funcionalidad de logout.

Por cierto, te están petando los tests!!

2023-03-31 16:22 UTC, Gazzell commented on src/components/Home.js
> +  /*return (
elimina los comentarios. Ya está todo en el repo y se puede rescatar si lo necesitas

2023-04-01 12:17 UTC, Guillermo-prog commented on src/components/Home.js
> +  /*return (
Okey, se me habia pasado este

2023-04-03 08:04 UTC, Gazzell approved these changes
Como decia, a ver si miramos esos logs

2023-04-03 08:04 UTC, merged