Guillermo prog patch 2
Gazzell/ludoteca-app pull request #2
Opened 2023-03-05 19:47 UTC by Guillermo-prog

2023-03-05 20:26 UTC, Gazzell requested changes
has metido muchas cosas que no tienen que ver con la configuración de firebase. Además, los mensajes de commit sin muy poco claros. Deja solo un commit con lo necesario para crear la cochera de firebase y como mucho inicializar firebase en el componente app

2023-03-05 20:26 UTC, Gazzell commented on package.json
> +    "react-router-dom": "^6.8.2",
esta dep no tiene que ver con la pr

2023-03-05 20:26 UTC, Gazzell commented on package.json
> +    "tailwindcss": "^3.2.7"
todo esto tampoco parece que tenga que ver con la pr

2023-03-05 20:26 UTC, Gazzell commented on src/App.js
> +  return <div>Hel</div>;
los cambios en este fichero tampoco tienen que ver con la configuración de firebase

2023-03-06 08:42 UTC, Gazzell commented
Una cosa para la próxima branch que hagas. Ponles nombres más específicos o relacionados con las tareas, por ejemplo `feat/connect_firebase`

2023-03-06 09:52 UTC, Guillermo-prog commented
Si, lo se, pero es muy difícil mantener completamente limpio el commit, ya que si por alguna razón no me pasan los hooks lo tengo que solucionar para subirlo. O por otro lado lo subo y no pasan los tests de CI, tengo que solucionarlo y hacer otro commit. Nose si hay alguna forma de evitar esto pero me parece complicado mantenerlo completamente limpio, evidentemente entiendo que seria lo adecuado. Lo intentaré para el próximo commit.

2023-03-06 09:58 UTC, Guillermo-prog commented
Una solución para tener un commit en vez de varios si necesito hacer mas de uno para que pasen los tests seria fusionar los commits en uno, no?

2023-03-06 17:00 UTC, Gazzell commented
puedes hacer `git commit --amend` para añadir tus cambios al último commit
o incluso un rebase interactivo `git rebase -i HEAD~3` y poner en todas las opciones de los commits que quieres quitar `f` (fixup)

2023-03-06 17:01 UTC, Gazzell commented
si quieres estamos un rato un mañana y te explico cómo hacerlo

2023-03-06 21:32 UTC, Guillermo-prog commented
Perfecto si, mañana cuando te venga bien me dices

2023-03-07 18:10 UTC, closed without merging