Navegacion entre rutas base
Gazzell/ludoteca-app pull request #7
Opened 2023-03-14 23:12 UTC by Guillermo-prog

2023-03-15 07:39 UTC, Gazzell commented on src/components/ProtectedRoute.js
qué es este fichero vacío?

2023-03-15 07:47 UTC, Gazzell requested changes
He intentado ejecutar el código y no me lleva a ningún sitio por defecto. Es ésto correcto?
De todas formas, en la descripción de la Pr deberías explicar alguna forma de probar lo que se ha hecho en la PR.

2023-03-16 11:05 UTC, Guillermo-prog commented on src/components/ProtectedRoute.js
Es el componente que englobará las rutas protegidas, aquellas que solo se puedan acceder si se está autenticado.

2023-03-17 12:08 UTC, Guillermo-prog commented
He intentado resolver esto, pero tampoco veo exactamente el problema. Es decir, yo en local ejecuto la aplicación y luego abro en el navegador localhost:3000 y me lleva a la ruta raíz que renderiza el componente Home. Luego dependiendo de donde se lance la aplicación se podrá definir que ruta usar por defecto, no??

2023-03-17 14:05 UTC, Gazzell approved these changes

2023-03-17 14:05 UTC, merged